import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'app/auth/screens/login_screen.dart'; // Ensure this path is correct

// Import firebase_options.dart if you have it (usually generated by FlutterFire CLI)
// import 'firebase_options.dart'; 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Ideal initialization with options from firebase_options.dart:
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );
  // Fallback initialization if firebase_options.dart is not available:
  await Firebase.initializeApp(); 
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Umrah Travel Agent',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const LoginScreen(), // Set LoginScreen as the home screen
    );
  }
}
